#!/bin/sh

operator=$(whoami)
srcdir=/opt/src
nproc=$(grep -c ^processor /proc/cpuinfo)
sudo="sudo"

main() {

  uid=$(id -u)
  if [ "${uid}" = "0" ]; then
     sudo=""
  fi

  if [ ! -d ${srcdir} ]; then
     $sudo mkdir -pv ${srcdir}
  fi
  $sudo chown -R ${operator}: ${srcdir}
  
#   if [ -e /etc/redhat-release ]; then
#	   $sudo yum -y update
#	   $sudo yum -y install git gcc make ncurses-devel 
#   elif [ -e /etc/alpine-release ]; then
#      $sudo apk update
#      $sudo apk add musl-dev git gcc make ncurses-dev
#   elif [ -e /etc/debian_version ]; then
#      $sudo apt-get -y update
#      $sudo apt-get -y install git gcc make libncurses-dev
#   else
#	   echo "Your distribution is not supported yet!"
#	   exit 23
#   fi

  cd ${srcdir}
  if [ ! -d busybox ]; then
     echo "Cloning github busybox repository..."
     git clone git://busybox.net/busybox.git
  fi
  
  cd ${srcdir}/busybox
  make clean
  git pull
  make defconfig
  make -j $nproc

  sudo cp -iv busybox /usr/local/bin

}

main $@
