#!/bin/bash

operator=$(whoami)
srcdir=/opt/src
platform=linux
nproc=$(grep -c ^processor /proc/cpuinfo)
sudo="sudo"
luaversion="5.4.4"
curversion=

main() {

	which lua && {
		curversion=$(lua -v | awk '{print $2}')
		[ "${curversion}" == "${luaversion}" ] && {
			warn "lua version ${curversion} already installed"
			exit 0
		}
	} || {
		echo "lua not found"
	}

	uid=$(id -u)
	if [ "${uid}" = "0" ]; then
		sudo=""
	fi

	[ -d ${srcdir} ] || $sudo mkdir -pv ${srcdir}
	$sudo chown -R ${operator}: ${srcdir}

	if [ -e /etc/redhat-release ]; then
		$sudo yum -y update
		$sudo yum -y install gcc make readline-devel curl
	elif [ -e /etc/alpine-release ]; then
		$sudo apk update
		$sudo apk add musl-dev gcc make readline-dev curl
	elif [ -e /etc/debian_version ]; then
		$sudo apt-get -y update
		$sudo apt-get -y install gcc make libreadline-dev curl
	else
		echo "Your distribution is not supported yet!"
		exit 23
	fi

	cd ${srcdir}
	[ -d lua ] && $sudo rm -f lua
	echo "Downloading lua source code..."
	curl -s https://www.lua.org/ftp/lua-${luaversion}.tar.gz | tar xzf - -C /opt/src

	mv lua-${luaversion} lua
	cd lua
	make clean
	[ -f /usr/local/include/lua.h ] && $sudo make uninstall

	make ${platform} -j $nproc
	$sudo make install

	lua -v
	install_libs

}

install_libs() {
	lua_lib_path=$(lua -e "print(package.path)" | awk -F'?' '{print $1}')
	ok "lua library path found: ${lua_lib_path}"
	for file in lualibs/*.lua ; do
		#echo "${file} --> ${lua_lib_path}"
		$sudo cp -uv "${file}" "${lua_lib_path}"
		$sudo chown -Rv root: "${lua_lib_path}"
	done
}

main $@
