#!/bin/bash

operator=$(whoami)
srcdir=/opt/src
platform=linux
nproc=$(grep -c ^processor /proc/cpuinfo)
sudo="sudo"
sqlitedownloadurl="http://sqlite.org/2017/sqlite-amalgamation-3200100.zip"
sqliteversion="3.20.1"

main() {

  uid=$(id -u)
  if [ "${uid}" = "0" ]
  then
     sudo=""
  fi

  if [ ! -d ${srcdir} ]
  then
     $sudo mkdir -pv ${srcdir}
  fi
  $sudo chown -R ${operator} ${srcdir}

  if [ -e /etc/redhat-release ]; then
	  $sudo yum -y update
	  $sudo yum -y install git gcc make readline-devel curl ncurses-devel sudo
  elif [ -e /etc/alpine-release ]; then
     $sudo apk update
     $sudo apk add musl-dev git gcc make readline-dev curl ncurses-dev sudo
  elif [ -e /etc/debian_version ]; then
     $sudo apt-get -y update
     $sudo apt-get -y install git gcc make libreadline-dev curl libncurses-dev sudo
  else
     echo "Your distribution is not supported yet!"
     exit 23
  fi

  cd ${srcdir}
  if [ ! -d sqlite ]; then
    echo "Downloading sqlite..."
    $sudo curl -s ${sqlitedownloadurl} -o sqlitearchive.zip
    $sudo unzip sqlitearchive.zip
    $sudo rm sqlitearchive.zip
    $sudo mv sqlite-amalgamation-* sqlite
  fi
  cd sqlite
  $sudo bash -c 'cat << EOF > makefile
# Makefile

CC = gcc
CCFLAGS = -Wall -std=c99 -O2

sqlite3: sqlite3.c
	\$(CC) \$(CCFLAGS) -DHAVE_READLINE shell.c sqlite3.c -lpthread -ldl -lreadline -o sqlite3
	strip sqlite3

clean:
	rm -f sqlite3 sqlite3.o

install:
	sudo cp -f sqlite3 /usr/local/bin

uninstall:
	sudo rm -f /usr/local/bin/sqlite3
EOF'
  
  $sudo make sqlite3
  $sudo make install

}

main $@
