#!/bin/sh

operator=$(whoami)
srcdir=/opt/src
nproc=$(grep -c ^processor /proc/cpuinfo)
sudo="sudo"
version="3.41.0"

main() {

	checkAlready

	uid=$(id -u)
	if [ "${uid}" = "0" ]; then
		sudo=""
	fi

	if [ ! -d ${srcdir} ]; then
		$sudo mkdir -pv ${srcdir}
	fi
	$sudo chown -R ${operator}: ${srcdir}
	
	if ! which gcc ; then
		if [ -e /etc/redhat-release ]; then
			$sudo yum -y update
			$sudo yum -y install git gcc make ncurses-devel 
		elif [ -e /etc/alpine-release ]; then
			$sudo apk update
			$sudo apk add musl-dev git gcc make ncurses-dev
		elif [ -e /etc/debian_version ]; then
			$sudo apt-get -y update
			$sudo apt-get -y install git gcc make libncurses-dev
		else
			echo "Your distribution is not supported yet!"
			exit 23
		fi
	fi

	cd ${srcdir}
	if [ ! -d sqlite ]; then
		echo "Cloning github sqlite repository..."
		git clone https://github.com/sqlite/sqlite.git
	fi
	
	cd ${srcdir}/sqlite
	make clean
	git pull

	git checkout version-${version}
	./configure

	make sqlite3 sqldiff -j $nproc
	$sudo make install

}

checkAlready() {
	echo -n "sqlite3: "
  # sqlite3 installed at all?
	which sqlite3 || { echo "sqlite3 not found!" ; exit 60 ; }
	# extract current sqlite version
	current=$(sqlite3 --version | cut -d' ' -f 1)
	if [ "${current}" = "${version}" ] ; then
		echo "Version ${version} is already installed!"
		echo "Please set 'version' variable in script and try again"
		exit 23
	fi
}

main $@

# Found here: https://github.com/nalgeon/sqlite/blob/3.39.1/.github/workflows/build.yml
# A way to build with all (?) options, for ubuntu:
#
# gcc \
#                    -DHAVE_READLINE \
#                    -DSQLITE_ENABLE_DBPAGE_VTAB \
#                    -DSQLITE_ENABLE_DBSTAT_VTAB \
#                    -DSQLITE_ENABLE_EXPLAIN_COMMENTS \
#                    -DSQLITE_ENABLE_FTS4 \
#                    -DSQLITE_ENABLE_FTS5 \
#                    -DSQLITE_ENABLE_GEOPOLY \
#                    -DSQLITE_ENABLE_JSON1 \
#                    -DSQLITE_ENABLE_MATH_FUNCTIONS \
#                    -DSQLITE_ENABLE_OFFSET_SQL_FUNC \
#                    -DSQLITE_ENABLE_RTREE \
#                    -DSQLITE_ENABLE_STAT4 \
#                    -DSQLITE_ENABLE_STMTVTAB \
#                    -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION \
#                    -DSQLITE_HAVE_ZLIB \
#                    -DSQLITE_LIKE_DOESNT_MATCH_BLOBS \
#                    -DSQLITE_THREADSAFE=0 \
#                    -DUSE_URI \
#                    src/shell.c src/sqlite3.c -o sqlite3 \
#                    -ldl -lz -lm -lreadline -lncurses
