#!/bin/sh

operator=$(whoami)
srcdir=../sqlite/sqlite-3.17.0
platform=linux
nproc=$(grep -c ^processor /proc/cpuinfo)
sudo="sudo"

main() {

   uid=$(id -u)
   if [ "${uid}" = "0" ]
   then
      sudo=""
   fi

   if [ -e /etc/redhat-release ]; then
	   $sudo yum -y update
	   $sudo yum -y install git gcc make readline-devel curl ncurses-devel sudo
   elif [ -e /etc/alpine-release ]; then
      $sudo apk update
      $sudo apk add musl-dev git gcc make readline-dev curl ncurses-dev sudo
   elif [ -e /etc/debian_version ]; then
      $sudo apt-get -y update
      $sudo apt-get -y install git gcc make libreadline-dev curl libncurses-dev sudo
   else
      echo "Your distribution is not supported yet!"
      exit 23
   fi

   cd ${srcdir}

   make sqlite3 lsqlite3
   $sudo make install

}

main $@
