#!/bin/sh

operator=$(whoami)
srcdir=/opt/src
nproc=$(grep -c ^processor /proc/cpuinfo)
sudo="sudo"
version="3.38.5"

main() {

	uid=$(id -u)
	if [ "${uid}" = "0" ]; then
		sudo=""
	fi

	if [ ! -d ${srcdir} ]; then
		$sudo mkdir -pv ${srcdir}
	fi
	$sudo chown -R ${operator}: ${srcdir}
	
	if ! which gcc ; then
		if [ -e /etc/redhat-release ]; then
			$sudo yum -y update
			$sudo yum -y install git gcc make ncurses-devel 
		elif [ -e /etc/alpine-release ]; then
			$sudo apk update
			$sudo apk add musl-dev git gcc make ncurses-dev
		elif [ -e /etc/debian_version ]; then
			$sudo apt-get -y update
			$sudo apt-get -y install git gcc make libncurses-dev
		else
			echo "Your distribution is not supported yet!"
			exit 23
		fi
	fi

	cd ${srcdir}
	if [ ! -d sqlite ]; then
		echo "Cloning github sqlite repository..."
		git clone https://github.com/sqlite/sqlite.git
	fi
	
	cd ${srcdir}/sqlite
	make clean
	git pull

	git checkout version-${version}
	./configure

	make sqlite3 sqldiff -j $nproc
	$sudo make install

}

main $@
