#!/bin/sh

luaversion="5.4"
operator=$(whoami)
srcdir=/opt/src
nproc=$(grep -c ^processor /proc/cpuinfo)
sudo="sudo"

main() {

	[ -e /etc/debian_version ] || {
	   echo "This works only on debian-like distros"
	   exit 23
	}

	uid=$(id -u)
	if [ "${uid}" = "0" ]; then
	   sudo=""
	fi

	[ -d ${srcdir} ] || $sudo mkdir -pv ${srcdir}
	$sudo chown -R ${operator}: ${srcdir}
	
	$sudo apt-get -y update
	$sudo apt-get -y install git gcc make libncurses-dev \
		liblua${luaversion}-dev lua${luaversion}

	[ -d ${srcdir}/vim ] || {
		cd "${srcdir}"
		echo "Cloning github vim repository..."
		git clone https://github.com/vim/vim.git
	}

	cd ${srcdir}/vim
	git checkout master
	git pull
	latest_tag=$(git tag | tail -1)
	echo "Latest tag: ${latest_tag}"
	git checkout ${latest_tag} -b ${latest_tag}
	make clean

	./configure \
	--with-compiledby=lyderic \
	--with-features=huge \
	--enable-luainterp=yes \
	--enable-fail-if-missing

	$sudo make uninstall
	make -j $nproc || {
		echo "* * *   VIM BUILDING FAILED!  * * *"
		exit 42
	}
	$sudo make install

	git checkout master
	git branch --delete "${latest_tag}"

	vim --version | head -3

}

main $@
